//! Integration test against a REAL classic ZIM file, kept OUT of the repo.
//!
//! Set `ONDE_ZIM_FIXTURE=/path/to/file.zim` to enable. Without the variable
//! (CI default) every test reports a skip note and passes, keeping
//! `cargo test --workspace` green and CI-safe — same policy as the MBTiles
//! fixture of T17 (`ONDE_MBTILES_FIXTURE`).
//!
//! The reference fixture is generated by CPython + `lz4.block` + `zstandard`
//! (see `~/onde-models/fixtures/zim/make_fixture.py`), deliberately NOT by
//! this Rust crate, so reading it back validates cross-producer compatibility
//! of all three compression paths (none / LZ4 block / zstd frame).

use zim_parser::{extract_text_from_html, ZimError, ZimReader};

const ENV_FIXTURE: &str = "ONDE_ZIM_FIXTURE";

/// Returns the configured fixture path, or `None` when integration testing is
/// disabled. A set-but-unreadable path fails loudly: the operator explicitly
/// asked for that file.
fn fixture_path() -> Option<std::path::PathBuf> {
    let raw = std::env::var_os(ENV_FIXTURE)?;
    if raw.is_empty() {
        return None;
    }
    let path = std::path::PathBuf::from(&raw);
    if !path.is_file() {
        panic!("{ENV_FIXTURE} points to {raw:?} which is not a readable file");
    }
    Some(path)
}

fn skip(reason: &str) {
    println!("skip: {reason}");
}

#[test]
fn real_fixture_content_extraction_all_codes() {
    let Some(path) = fixture_path() else {
        skip(&format!("set {ENV_FIXTURE} to run this test"));
        return;
    };

    let mut reader = ZimReader::open(&path).expect("fixture must open");
    reader.load_index().expect("load_index on real file");

    // The reference fixture carries exactly three articles, one per
    // compression code (none / LZ4 / zstd) — cross-producer payloads.
    assert_eq!(reader.article_count(), 3);
    let urls = reader.article_urls();
    assert_eq!(urls.len(), 3);

    for url in &urls {
        let art = reader
            .get_article(url)
            .unwrap_or_else(|| panic!("missing {url}"));
        // Content must have been decoded from its cluster (not left empty):
        // every fixture article is HTML with a non-trivial body.
        assert!(
            !art.content.is_empty(),
            "article {url} decoded to empty content"
        );
        let text = extract_text_from_html(&art.content);
        assert!(text.contains("Synthetic classic ZIM article"), "{text:?}");
        assert_eq!(art.mime_type, "text/html");
        assert_eq!(art.namespace, 'A');
    }

    // Prefix-title search must resolve against the real dirents.
    let hits = reader.search("Article", 10);
    assert!(!hits.is_empty(), "search on real fixture returned nothing");
    for h in &hits {
        assert_eq!(h.namespace, 'A');
    }

    // Rank access and search must agree on the URL set.
    let first = urls[0].clone();
    let art = reader.get_article(&first).expect("rank access");
    assert_eq!(art.url, first);
}

#[test]
fn real_fixture_rejects_lookalikes() {
    // Guards stay active against files that merely exist nearby: opening an
    // absent path keeps producing a typed error (no panic on user paths).
    let err = ZimReader::open("/nonexistent/definitely-absent.zim").unwrap_err();
    assert!(matches!(err, ZimError::OutOfBounds { .. }), "{err}");
}
